name: flutter_nested_navigation
description: Nested stateful navigation with ShellRoute
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  go_router:
    git:
      url: https://github.com/g-30/flutter_packages.git
      path: packages/go_router/
      ref: nested-persistent-navigation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter:
